version: '3.8'

services:
  # Main AgroBot Raspberry Pi application
  agrobot-rpi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrobot-rpi-controller
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - /dev:/dev
      - /sys:/sys:ro
      - /proc:/proc:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/i2c-1:/dev/i2c-1
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    privileged: true
    network_mode: host

  # Redis for caching and message queuing
  redis:
    image: redis:7-alpine
    container_name: agrobot-redis
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: agrobot-network
    driver: bridge

